### ISSUE TITLE
Crash while using it for high resolution PHAsset images in UICollectionView

### ISSUE THREAD

**Issue by atulvuliv** [cuzv/PhotoBrowser#9]
It crashes for high resolution images like in camera roll in PHAsset format. Works fine for some times but when I try to open images 5-6 times, it crashes eventually. 

Using fine for low resolution images.

Looks like a memory issue. Please suggest some workaround. (May be increase the cache size).

Device: iPhone 6s

Thanks,
Atul

**Comment by cuzv** [comment]
Actually, I didn't deal image cache, just provide display function using system's `UIImageView`, and works fine for a fews month.

Please make sure that the memory issue isn't caused by UICollectionView, load dozens of high resolution image once using UICollectionView, without optimization measures, may leads to crash.

If you are certainty sure that  the crash is caused by this lib, please provide your image's quality size, I will run for a test.

**Comment by atulvuliv** [comment]
First of all apologies for replying late as I missed the notification from github. 

I couldn't verify if it was this library's fault. I thought the high resolution images were not being freed properly after view is deallocated. I did some image caching optimization in my app and it seems to be working fine for now. I will have a look once more when I get time.

Thank you so much for your amazing library to make our app look good.

Best,
Atul
